import {
  Bell,
  Blocks,
  Bot,
  Box,
  BriefcaseBusiness,
  ChartNoAxesCombined,
  CheckCircle2,
  CircleUserRound,
  Compass,
  Database,
  FilePlus2,
  FileCheck2,
  Files,
  FileText,
  GitBranch,
  Grid2X2,
  House,
  LayoutTemplate,
  Network,
  Play,
  ScanSearch,
  Settings,
  Sparkles,
  Star,
  Table2,
  Tags,
  Users,
  WandSparkles,
  Workflow,
} from "lucide-react";

const icons = {
  sparkles: Sparkles,
  "scan-search": ScanSearch,
  wand: WandSparkles,
  "file-text": FileText,
  "file-plus": FilePlus2,
  network: Network,
  workflow: Workflow,
  files: Files,
  "git-branch": GitBranch,
  table: Table2,
  software: Blocks,
  delivery: BriefcaseBusiness,
  game: Grid2X2,
  feedback: Bot,
  devops: Box,
  timesheet: Users,
  ai: Sparkles,
  plugin: Blocks,
  template: LayoutTemplate,
  solution: BriefcaseBusiness,
  home: House,
  spaces: Grid2X2,
  favorites: Star,
  teams: Users,
  notifications: Bell,
  discover: Compass,
  account: CircleUserRound,
  database: Database,
  check: CheckCircle2,
  chart: ChartNoAxesCombined,
  "file-check": FileCheck2,
  play: Play,
  tags: Tags,
  settings: Settings,
};

export function AppIcon({ name, size = 20, strokeWidth = 1.8, ...props }) {
  const Icon = icons[name] || Sparkles;
  return <Icon size={size} strokeWidth={strokeWidth} aria-hidden="true" {...props} />;
}
